"""descricao_da_migracao

Revision ID: 8179f46b1ed5
Revises: 02df95b50a3c
Create Date: 2025-07-29 12:28:10.444802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8179f46b1ed5'
down_revision: Union[str, Sequence[str], None] = '02df95b50a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificacoes',
    sa.Column('id_verificacao', sa.Integer(), nullable=False),
    sa.Column('id_voto', sa.UUID(), nullable=False),
    sa.Column('comprovante', sa.Text(), nullable=False),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_verificacao')
    )
    with op.batch_alter_table('verificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verificacoes_id_verificacao'), ['id_verificacao'], unique=False)

    op.create_table('relatorios',
    sa.Column('id_relatorio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('id_verificacao', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_verificacao'], ['verificacoes.id_verificacao'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_relatorio')
    )
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relatorios_id_relatorio'), ['id_relatorio'], unique=False)

    op.create_table('logs',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('id_verificacao', sa.Integer(), nullable=True),
    sa.Column('id_relatorio', sa.Integer(), nullable=True),
    sa.Column('assinatura', sa.String(length=64), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_relatorio'], ['relatorios.id_relatorio'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_verificacao'], ['verificacoes.id_verificacao'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_id_log'), ['id_log'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_id_log'))

    op.drop_table('logs')
    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relatorios_id_relatorio'))

    op.drop_table('relatorios')
    with op.batch_alter_table('verificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verificacoes_id_verificacao'))

    op.drop_table('verificacoes')
    # ### end Alembic commands ###
 