# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x03log\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n\nLogRequest\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x33\n\x0eid_verificacao\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\x0bvoto_valido\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x31\n\x0cid_relatorio\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"\x1e\n\x0cLogIdRequest\x12\x0e\n\x06id_log\x18\x01 \x01(\x05\"\xcc\x02\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x0e\n\x06id_log\x18\x03 \x01(\x05\x12\x0c\n\x04tipo\x18\x04 \x01(\t\x12\x11\n\tdescricao\x18\x05 \x01(\t\x12-\n\tdata_hora\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0eid_verificacao\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\x0bvoto_valido\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x31\n\x0cid_relatorio\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x12\n\nassinatura\x18\n \x01(\t\x12\x0e\n\x06valido\x18\x0b \x01(\x08\x32q\n\nLogService\x12\x31\n\x0cRegistrarLog\x12\x0f.log.LogRequest\x1a\x10.log.LogResponse\x12\x30\n\tBuscarLog\x12\x11.log.LogIdRequest\x1a\x10.log.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=84
  _globals['_LOGREQUEST']._serialized_end=282
  _globals['_LOGIDREQUEST']._serialized_start=284
  _globals['_LOGIDREQUEST']._serialized_end=314
  _globals['_LOGRESPONSE']._serialized_start=317
  _globals['_LOGRESPONSE']._serialized_end=649
  _globals['_LOGSERVICE']._serialized_start=651
  _globals['_LOGSERVICE']._serialized_end=764
# @@protoc_insertion_point(module_scope)
