# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import relatorio_pb2 as relatorio__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in relatorio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelatorioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GerarRelatorio = channel.unary_unary(
                '/relatorio.RelatorioService/GerarRelatorio',
                request_serializer=relatorio__pb2.RelatorioRequest.SerializeToString,
                response_deserializer=relatorio__pb2.RelatorioResponse.FromString,
                _registered_method=True)
        self.BuscarRelatorio = channel.unary_unary(
                '/relatorio.RelatorioService/BuscarRelatorio',
                request_serializer=relatorio__pb2.RelatorioIdRequest.SerializeToString,
                response_deserializer=relatorio__pb2.RelatorioResponse.FromString,
                _registered_method=True)


class RelatorioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GerarRelatorio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarRelatorio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelatorioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GerarRelatorio': grpc.unary_unary_rpc_method_handler(
                    servicer.GerarRelatorio,
                    request_deserializer=relatorio__pb2.RelatorioRequest.FromString,
                    response_serializer=relatorio__pb2.RelatorioResponse.SerializeToString,
            ),
            'BuscarRelatorio': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarRelatorio,
                    request_deserializer=relatorio__pb2.RelatorioIdRequest.FromString,
                    response_serializer=relatorio__pb2.RelatorioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relatorio.RelatorioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relatorio.RelatorioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelatorioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GerarRelatorio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relatorio.RelatorioService/GerarRelatorio',
            relatorio__pb2.RelatorioRequest.SerializeToString,
            relatorio__pb2.RelatorioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarRelatorio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relatorio.RelatorioService/BuscarRelatorio',
            relatorio__pb2.RelatorioIdRequest.SerializeToString,
            relatorio__pb2.RelatorioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
