# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relatorio.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'relatorio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frelatorio.proto\x12\trelatorio\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x10RelatorioRequest\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x0f\n\x07\x66ormato\x18\x02 \x01(\t\x12\x33\n\x0eid_verificacao\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x12\n\ncriado_por\x18\x04 \x01(\t\"*\n\x12RelatorioIdRequest\x12\x14\n\x0cid_relatorio\x18\x01 \x01(\x05\"\x9f\x01\n\x11RelatorioResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x14\n\x0cid_relatorio\x18\x03 \x01(\x05\x12\x0f\n\x07\x63\x61minho\x18\x04 \x01(\t\x12-\n\tdata_hora\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncriado_por\x18\x06 \x01(\t2\xaf\x01\n\x10RelatorioService\x12K\n\x0eGerarRelatorio\x12\x1b.relatorio.RelatorioRequest\x1a\x1c.relatorio.RelatorioResponse\x12N\n\x0f\x42uscarRelatorio\x12\x1d.relatorio.RelatorioIdRequest\x1a\x1c.relatorio.RelatorioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relatorio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELATORIOREQUEST']._serialized_start=95
  _globals['_RELATORIOREQUEST']._serialized_end=217
  _globals['_RELATORIOIDREQUEST']._serialized_start=219
  _globals['_RELATORIOIDREQUEST']._serialized_end=261
  _globals['_RELATORIORESPONSE']._serialized_start=264
  _globals['_RELATORIORESPONSE']._serialized_end=423
  _globals['_RELATORIOSERVICE']._serialized_start=426
  _globals['_RELATORIOSERVICE']._serialized_end=601
# @@protoc_insertion_point(module_scope)
