# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verificacao.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'verificacao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11verificacao.proto\x12\x0bverificacao\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n\x12VerificacaoRequest\x12\r\n\x05votos\x18\x01 \x01(\x05\x12\x0f\n\x07recibos\x18\x02 \x01(\x05\x12\x12\n\ncriado_por\x18\x03 \x01(\t\".\n\x14VerificacaoIdRequest\x12\x16\n\x0eid_verificacao\x18\x01 \x01(\x05\"\x81\x01\n\x13VerificacaoResponse\x12\x16\n\x0eid_verificacao\x18\x01 \x01(\x05\x12\x11\n\tresultado\x18\x02 \x01(\x08\x12\x10\n\x08mensagem\x18\x03 \x01(\t\x12-\n\tdata_hora\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xa5\x02\n\x12VerificacaoService\x12X\n\x13\x45xecutarVerificacao\x12\x1f.verificacao.VerificacaoRequest\x1a .verificacao.VerificacaoResponse\x12X\n\x11\x42uscarVerificacao\x12!.verificacao.VerificacaoIdRequest\x1a .verificacao.VerificacaoResponse\x12[\n\x12StreamVerificacoes\x12!.verificacao.VerificacaoIdRequest\x1a .verificacao.VerificacaoResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verificacao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFICACAOREQUEST']._serialized_start=67
  _globals['_VERIFICACAOREQUEST']._serialized_end=139
  _globals['_VERIFICACAOIDREQUEST']._serialized_start=141
  _globals['_VERIFICACAOIDREQUEST']._serialized_end=187
  _globals['_VERIFICACAORESPONSE']._serialized_start=190
  _globals['_VERIFICACAORESPONSE']._serialized_end=319
  _globals['_VERIFICACAOSERVICE']._serialized_start=322
  _globals['_VERIFICACAOSERVICE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
