# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import verificacao_pb2 as verificacao__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in verificacao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VerificacaoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutarVerificacao = channel.unary_unary(
                '/verificacao.VerificacaoService/ExecutarVerificacao',
                request_serializer=verificacao__pb2.VerificacaoRequest.SerializeToString,
                response_deserializer=verificacao__pb2.VerificacaoResponse.FromString,
                _registered_method=True)
        self.BuscarVerificacao = channel.unary_unary(
                '/verificacao.VerificacaoService/BuscarVerificacao',
                request_serializer=verificacao__pb2.VerificacaoIdRequest.SerializeToString,
                response_deserializer=verificacao__pb2.VerificacaoResponse.FromString,
                _registered_method=True)
        self.StreamVerificacoes = channel.unary_stream(
                '/verificacao.VerificacaoService/StreamVerificacoes',
                request_serializer=verificacao__pb2.VerificacaoIdRequest.SerializeToString,
                response_deserializer=verificacao__pb2.VerificacaoResponse.FromString,
                _registered_method=True)


class VerificacaoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutarVerificacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarVerificacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamVerificacoes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VerificacaoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutarVerificacao': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutarVerificacao,
                    request_deserializer=verificacao__pb2.VerificacaoRequest.FromString,
                    response_serializer=verificacao__pb2.VerificacaoResponse.SerializeToString,
            ),
            'BuscarVerificacao': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarVerificacao,
                    request_deserializer=verificacao__pb2.VerificacaoIdRequest.FromString,
                    response_serializer=verificacao__pb2.VerificacaoResponse.SerializeToString,
            ),
            'StreamVerificacoes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamVerificacoes,
                    request_deserializer=verificacao__pb2.VerificacaoIdRequest.FromString,
                    response_serializer=verificacao__pb2.VerificacaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verificacao.VerificacaoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('verificacao.VerificacaoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VerificacaoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutarVerificacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verificacao.VerificacaoService/ExecutarVerificacao',
            verificacao__pb2.VerificacaoRequest.SerializeToString,
            verificacao__pb2.VerificacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarVerificacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/verificacao.VerificacaoService/BuscarVerificacao',
            verificacao__pb2.VerificacaoIdRequest.SerializeToString,
            verificacao__pb2.VerificacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamVerificacoes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/verificacao.VerificacaoService/StreamVerificacoes',
            verificacao__pb2.VerificacaoIdRequest.SerializeToString,
            verificacao__pb2.VerificacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
